title: Portfolio
author: 
email: kyremortiz23@gmail.com
description: >- 
  I walk around the world, capturing the essence of my surroungdings.  

social:
  instagram: kyremortiz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true

url: "https://kyremortiz.github.io"
