title: Portfolio
author: Kyrem
email: kyremortiz23@gmail.com
description: >- 
  Capturing the essence of my surroundings.  

social:
  instagram: kyremortiz
  youtube: kykyvlogs

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true

url: "https://kyremortiz.github.io"
